[tools]
msg_extractor = "tools/REMSG_Converter/msg2json.bat"
data_extractor = "tools/DotUserReader/bin/Release/net8.0/DotUserReader.exe"

[io]
data_dir = "./data"
output_dir = "./output"

[extract]
prefix = "natives/STM/GameDesign/Common"
files = [
    "Equip/AccessoryData.user.3",
    "Equip/AmuletData.user.3",
    "Equip/AmuletRecipeData.user.3",
    "Equip/ArmorData.user.3",
    "Equip/ArmorRecipeData.user.3",
    "Equip/ArmorSeriesData.user.3",
    "Equip/ArmorUpgradeData.user.3",
    "Equip/Charm.user.3",
    "Equip/SkillCommonData.user.3",
    "Equip/SkillData.user.3",
    "Item/itemData.user.3",
    "Item/ItemRecipe.user.3",
    "Equip/RodInsectRecipeData.user.3",
    "Equip/WeaponSeriesData.user.3",
    "Equip/BowgunCustomizeData.user.3",
    "Equip/BowgunCustomizeItemData.user.3",
    "Weapon/*.user.3",
]

[extract.rules."Weapon/*.user.3"]
match = "Tree\\.user\\.3$"
rsz_indexes = [2]

[translations]
prefix = "natives/STM/GameDesign/Text"
files = [
    "Excel_Equip/Accessory.msg.23",
    "Excel_Equip/Amulet.msg.23",
    "Excel_Equip/Armor.msg.23",
    "Excel_Equip/ArmorSeries.msg.23",
    "Excel_Equip/Charm.msg.23",
    "Excel_Equip/Skill.msg.23",
    "Excel_Equip/SkillCommon.msg.23",
    "Excel_Data/Item.msg.23",
    "Excel_Equip/Bow.msg.23",
    "Excel_Equip/BowgunCustomize.msg.23",
    "Excel_Equip/ChargeAxe.msg.23",
    "Excel_Equip/GunLance.msg.23",
    "Excel_Equip/Hammer.msg.23",
    "Excel_Equip/HeavyBowgun.msg.23",
    "Excel_Equip/Lance.msg.23",
    "Excel_Equip/LightBowgun.msg.23",
    "Excel_Equip/LongSword.msg.23",
    "Excel_Equip/Rod.msg.23",
    "Excel_Equip/RodInsect.msg.23",
    "Excel_Equip/ShortSword.msg.23",
    "Excel_Equip/SlashAxe.msg.23",
    "Excel_Equip/Tachi.msg.23",
    "Excel_Equip/TwinSword.msg.23",
    "Excel_Equip/WeaponSeries.msg.23",
    "Excel_Equip/Whistle.msg.23",
]
